name: Build and Release (Linux)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build webapp và gói phát hành
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Thiết lập Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Cài đặt dependencies
        run: yarn install --frozen-lockfile

      - name: Build (webapp)
        run: yarn build

      - name: Đóng gói webapp.zip
        run: |
          sudo apt-get update -y
          sudo apt-get install -y zip
          zip -r webapp.zip webapp

      - name: Xác định tên release
        id: meta
        run: |
          # Tạo tên release từ commit hash và timestamp
          COMMIT_HASH=$(echo ${{ github.sha }} | cut -c1-7)
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          RELEASE_NAME="build-${TIMESTAMP}-${COMMIT_HASH}"
          echo "name=$RELEASE_NAME" >> $GITHUB_OUTPUT
          echo "tag=$RELEASE_NAME" >> $GITHUB_OUTPUT

      - name: Tạo Release và upload webapp.zip
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.meta.outputs.tag }}
          name: ${{ steps.meta.outputs.name }}
          generate_release_notes: true
          files: |
            webapp.zip
        


